server:
    port: 8888

spring:
    cloud:
      config:
        server:
          git:
            uri: https://github.com/ARNIXMINADEO/java-practice/config-data
            basedir: config-data
            default-label: main
            username: ${GIT_USER}
            password: ${GIT_PASSWORD}
    security:
      user:
        name: root
        password: s3cr3t3