server:
    port: 8081

spring:
    cloud:
      config:
        server:
          git:
            uri: https://github.com/ARNIXMINADEO/java-practice
            username: ${GIT_USER}
            password: ${GIT_PASSWORD}
            default-label: devel
            searchPaths: config-data

    security:
      user:
        name: root
        password: root


        application:
          name: java-practice
          profiles:
            active: default,service,test

    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          show-details: ALWAYS
  
