server:
    port: 8081

spring:
    cloud:
      config:
        server:
          git:
            uri: https://github.com/ARNIXMINADEO/java-practice.git
            username: ${GIT_USER}
            password: ${GIT_PASSWORD}
            default-label: devel
    security:
      user:
        name: root
        password: root


        application:
          name: java-practice
          profiles:
            active: default